apiVersion: batch/v1
kind: CronJob
metadata:
  name: dotnet-cronjob
spec:
  schedule: "*/1 * * * *"  # Every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dotnet-task
            image: sc3p73r/job-dotnet:latest
            command: ["dotnet", "DotnetJob.dll"]
          restartPolicy: Never
