apiVersion: batch/v1
kind: Job
metadata:
  name: dotnet-job
spec:
  template:
    spec:
      containers:
      - name: dotnet-task
        image: sc3p73r/job-dotnet:latest
        command: ["dotnet", "DotnetJob.dll"]
      restartPolicy: Never

